control_brace_style = "ClosingNextLine"
fn_params_layout = "vertical"
fn_single_line = true
merge_imports = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
style_edition = "2024"
tab_spaces = 2
